Update RelevanceRealization.md
zkSNACKs/zIPs pull request #90
Opened 2022-12-15 13:24 UTC by bfiics

2022-12-15 14:22 UTC, MaxHillebrand approved these changes

2022-12-15 23:20 UTC, yahiheb requested changes

2022-12-15 23:20 UTC, yahiheb commented on RelevanceRealization.md
>  0. If issue is in the Doing status must add Assignees to the card the doers and their coordinator as well.
```suggestion
0. If issue is in the `Doing` status must add `Assignees` to the card the doers and their coordinator as well.   
```

2022-12-16 08:12 UTC, yahiheb approved these changes

2022-12-16 15:19 UTC, merged