RoundRobin.md
zkSNACKs/zIPs pull request #92
Opened 2023-03-30 12:35 UTC by Pule08

2023-03-30 12:37 UTC, MaxHillebrand approved these changes

2023-03-31 04:56 UTC, nopara73 requested changes
Very good. Make sure to update https://github.com/zkSNACKs/zIPs#readme as well

2023-04-09 07:19 UTC, MaxHillebrand approved these changes

2023-04-18 09:11 UTC, molnard approved these changes

2023-04-18 09:12 UTC, molnard commented
@Pule08 do you know how to update https://github.com/zkSNACKs/zIPs#readme in this PR?

2023-04-19 20:34 UTC, Pule08 commented on RoundRobin.md
> +License: lol
I copied it from the relevance zIP.

2023-04-20 03:25 UTC, nopara73 commented on RoundRobin.md
> +License: lol
"LOL" is an acronym that stands for "laugh out loud." It is commonly used in text messages, social media, and online conversations to indicate that the sender finds something funny or amusing. The phrase is typically used to express humor, amusement, or lightheartedness.

2023-04-20 03:26 UTC, nopara73 commented
Sister PR: https://github.com/zkSNACKs/zIPs/pull/93

2023-04-20 07:17 UTC, Pule08 commented on RoundRobin.md
> +License: lol
That was my first thought :D

2023-04-20 12:29 UTC, molnard approved these changes
🥇

2023-04-21 03:12 UTC, merged